[package]
name = "patches"
version = "0.1.0"
authors = ["aesCyprian <aesCyprian@protonmail.ch>"]
edition = "2018"

[dependencies]
clap = "3.0.0-beta.2"
goblin = "0.2.3"

[profile.release]
lto = true
opt-level = "z"
